// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjSY7QnDeh7XDuANJK3n4Uo9gZkf7qjqI',
    appId: '1:383413930503:web:15a1f9343678e22739b8a2',
    messagingSenderId: '383413930503',
    projectId: 'mynotes-368d1',
    authDomain: 'mynotes-368d1.firebaseapp.com',
    storageBucket: 'mynotes-368d1.firebasestorage.app',
    measurementId: 'G-W67RT4NDQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLvufBvBEkO0z7Hr8EqaRzTBjX8E3Oris',
    appId: '1:383413930503:android:9eddb443141e66a939b8a2',
    messagingSenderId: '383413930503',
    projectId: 'mynotes-368d1',
    storageBucket: 'mynotes-368d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAry2yZC0BshGZo4x6HLS_DA_hKkTbeeI',
    appId: '1:383413930503:ios:6b38a5a72e61ff6a39b8a2',
    messagingSenderId: '383413930503',
    projectId: 'mynotes-368d1',
    storageBucket: 'mynotes-368d1.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAry2yZC0BshGZo4x6HLS_DA_hKkTbeeI',
    appId: '1:383413930503:ios:6b38a5a72e61ff6a39b8a2',
    messagingSenderId: '383413930503',
    projectId: 'mynotes-368d1',
    storageBucket: 'mynotes-368d1.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjSY7QnDeh7XDuANJK3n4Uo9gZkf7qjqI',
    appId: '1:383413930503:web:cd82d3e6905ae5f939b8a2',
    messagingSenderId: '383413930503',
    projectId: 'mynotes-368d1',
    authDomain: 'mynotes-368d1.firebaseapp.com',
    storageBucket: 'mynotes-368d1.firebasestorage.app',
    measurementId: 'G-D3VHXZLJM9',
  );

}